sources:
  - FunnelSans.glyphs
familyName: "Funnel Sans"
axisOrder:
  - wght
stat:
  FunnelSans[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
    - name: Medium
      value: 500
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
outputDir: "../fonts"
buildTTF: true
buildOTF: true
autohintTTF: true
